---
- name: Deploy cAdvisor
  community.docker.docker_container:
    name: "{{ cadvisor_container_name }}"
    image: "{{ cadvisor_image }}"
    ports:
      - "{{ cadvisor_port }}:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true
    devices:
      - "/dev/kmsg"
    networks:
      - name: "{{ network_name }}"
    restart_policy: always
  retries: "{{ task_retries }}"
  delay: "{{ task_delay }}"
