---
groups:
  - name: container.rules
    rules:
      - alert: HighCPUUsage
        expr: rate(container_cpu_usage_seconds_total{name=~".+"}[5m]) > 0.9
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage in container '{{ $labels.name }}'"
          description: "Container '{{ $labels.name }}' is using >90% CPU for 2 minutes. Image: {{ $labels.image }}"

      - alert: HighMemoryUsage
        expr: container_memory_usage_bytes{name=~".+"} > (1024 * 1024 * 1024)
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage in container '{{ $labels.name }}'"
          description: "Container '{{ $labels.name }}' is using >90% memory. Image: {{ $labels.image }}"

      - alert: ContainerDown
        expr: (time() - container_last_seen{name=~".+"}) > 120
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Container '{{ $labels.name }}' is DOWN"
          description: "Container '{{ $labels.name }}' has not been seen for over 2 minutes. Image: {{ $labels.image }}"
