---
- name: Enable NTP sync via timedatectl
  ansible.builtin.command:
     cmd: timedatectl set-ntp true

- name: Update APT cache if outdated
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400

- name: Install prerequisites for Docker CE repository
  ansible.builtin.package:
    name:
      - gnupg
      - apt-transport-https
      - ca-certificates
      - curl
    state: present

- name: Ensure keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    owner: root
    group: root

- name: Add Docker stable APT repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/ubuntu
      {{ ansible_distribution_release }} stable
    state: present
    filename: docker

- name: Install Docker CE and Python requirements
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - python3-pip
      - python3-docker
    state: present

- name: Ensure containerd service is enabled and running
  ansible.builtin.service:
    name: containerd
    state: started
    enabled: true

- name: Ensure Docker socket unit is enabled and running
  ansible.builtin.service:
    name: docker.socket
    state: started
    enabled: true

- name: Ensure Docker service is enabled and running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Create Docker network
  community.docker.docker_network:
    name: "{{ network_name }}"
    driver: bridge
    state: present

- name: Ensure 'docker' group exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user 'ansible' to the 'docker' group
  ansible.builtin.user:
    name: "{{ ansible_user_name }}"
    groups: docker
    append: yes
