- name: Deploy monitoring clients (NODES)
  hosts: monitoring_clients
  become: true
  vars_files:
    - ../group_vars/all.yml

  roles:
    - setup
    - promtail
    - node-exporter
    - cadvisor

- name: Refresh Prometheus target config
  hosts: monitoring_clients
  become: true
  tasks:
    - name: Run prometheus-targets role on server
      import_role:
        name: prometheus-targets
      delegate_to: server
      run_once: true
